services:
  app:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/app/src
    depends_on:
      - server
    networks:
      - vpn-1
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - ./server:/usr/app/src
    networks:
      - vpn-1

networks:
  vpn-1:
