apiVersion: skaffold/v4beta11
kind: Config
manifests: # helps redirect skaffold to a custom directory
  rawYaml:
    - k8s-dev/*
build: # doesnot push the image to dockerhub everytime we make a change
  local:
    push: false
  artifacts:
    - image: sanyamgupta23/vpc-app-skaffold
      context: web
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*"
            dest: .
    - image: sanyamgupta23/server-app-skaffold
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*"
            dest: .
# Notes:
# 1) Donot set imagePullPolicy : Always in k8s depl file, else skaffold will try to pull the image
