apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: app
          image: us-docker.pkg.dev/vpc-1-439422/gcr.io/vpc-app:v2
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          imagePullPolicy: Always
