FROM python:3.11-slim

WORKDIR /usr/app/src

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8081

ENV FLASK_APP=app.py

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=8081", "--debug"]
