apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: vpc-app
          image: sanyamgupta23/vpc-app-skaffold
          ports:
            - containerPort: 8080
